services:
  server:
    volumes:
      - ./packages/server:/app
    command: sh -c "npm install && npm run dev"

  client:
    volumes:
      - ./packages/client:/app
      - /app/node_modules
    command: npm run dev:docker

  worker:
    volumes:
      - ./packages/server:/app
    command: sh -c "npm install && npm run start:worker"
