name: Build and Push Multi-Service Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitly-server:latest

  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitly-client:latest
          build-args: |
            ACTUAL_SERVER_API_URL=${{ secrets.ACTUAL_SERVER_API_URL }}

  build-and-push-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/server # Using the same context as the server
          target: worker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitly-worker:latest
